### ISSUE TITLE
Team page broken

### ISSUE THREAD

**Issue by HengchengZhang** [QuantEcon/website#97] opened 2023-06-01 04:23 UTC
Hi @DrDrij and @jstac, I just randomly noticed that the team page is broken https://quantecon.org/team/

**Comment by jstac** [comment] 2023-06-01 04:29
Thanks @HengchengZhang , nice catch!  @DrDrij , could this be caused by your last commit?

**Comment by DrDrij** [comment] 2023-06-01 11:34
Thanks both. Team page was merged into the About page. I need to remove it from the navigation.

**Comment by DrDrij** [comment] 2023-06-06 02:09
Fixed the navigation bug. See About page for Team content.

**Closed** 2023-06-06 03:07 UTC
